Merge yamdi and yamdi-utils.

diff --git a/src/yamdi b/src/yamdi
--- a/src/yamdi
+++ b/src/yamdi
@@ -1,7 +1,213 @@
 #!/bin/sh
 
-# Quit on error.
+# Quit on error and disallow undefined variable substitution.
 set -e
+
+# Prints a debug message, if enabled.
+# Arguments:
+#   - The message.
+# Outputs:
+#   - The formatted message.
+debug() {
+  if [ "$YAMDI_DEBUG" = "true" ]; then
+    printf "[$(date +%R:%S) DEBUG]: [YAMDI] %s\n" "$*"
+  fi
+}
+
+# Prints an info message.
+# Arguments:
+#   - The message.
+# Outputs:
+#   - The formatted message.
+info() {
+  printf "[$(date +%R:%S) INFO]: [YAMDI] %s\n" "$*"
+}
+
+# Prints a warning message.
+# Arguments:
+#   - The message.
+# Outputs:
+#   - The formatted message.
+warning() {
+  printf "[$(date +%R:%S) WARNING]: [YAMDI] %s\n" "$*"
+}
+
+# Prints an error message.
+# Arguments:
+#   - The message.
+# Outputs:
+#   - The formatted message.
+error() {
+  printf "[$(date +%R:%S) ERROR]: [YAMDI] %s\n" "$*"
+}
+
+# Given a resource, gets the path to its respective writable copy in the user directory.
+# Arguments:
+#   - The original directory, that may not be writable.
+# Outputs:
+#   - The corresponding user subdirectory, that should be writable.
+make_user_path() {
+  printf %s "$USER_DIRECTORY/$(basename "$1")-copy"
+}
+
+# Initializes a new temporary Git directory, makes a commit for it, and merges its contents with a
+# given directory, using Git. It's very important that, if Git will be used after this function be
+# called, that `unset GIT_DIR GIT_WORK_TREE` is ran. For more details on the checkout method used
+# here, see: https://gitolite.com/deploy.html
+# Arguments:
+#   - Path to the source directory.
+#   - Path to the target directory.
+# Outputs:
+#   - Status messages.
+# Variables Exported:
+#   - GIT_DIR: Location of the Git directory.
+#   - GIT_WORK_TREE: Location of the Git work tree.
+import_directory() {
+  source_directory=$1
+  target_directory=$2
+
+  # If the directory is empty or doesn't exist. An unmounted Docker volume should be an empty
+  # directory. (TODO: update this comment)
+  if [ -z "$(ls -A "$source_directory")" ] || [ ! -d "$source_directory" ]; then
+    warning "No files to import."
+    return 0
+  fi
+
+  debug "Making copy of host files."
+  source_directory_copy=$(make_user_path "$source_directory")
+  # Ensure that the VCS directory isn't present to begin with, because if it is then the source
+  # directory will be copied inside of the VCS directory, effectively discarding any new changes.
+  rm -rf "$source_directory_copy"
+  cp -R "$source_directory" "$source_directory_copy"
+
+  debug "Initializing Git repo."
+  # Use a temporary Git directory. This reduces the need for maintining a repo externally, and
+  # reduces any conflict with a preexisting repo.
+  export GIT_DIR="$source_directory_copy/.git-yamdi"
+  # For now, use the source directory as Git's working directory, to copy the initial changes.
+  export GIT_WORK_TREE="$source_directory_copy"
+  # Initialize the temporary directory, if it hasn't already been initialized.
+  git init -q
+
+  debug "Making Git commit."
+  # Add all files from the directory from the stage. This also stages deletions.
+  git add -A
+  # Remove our temporary Git directory from the stage.
+  git reset -q -- "$GIT_DIR"
+  # Make a commit. This is necessary because otherwise, we can't really use this repo for anything.
+  # Procede even if failed because that probably just means there haven't been any configuration
+  # changes.
+  COMMAND="git commit -m \"Automatically generated commit.\""
+  if [ "$YAMDI_DEBUG" = "true" ]; then
+    eval "$COMMAND" || true
+  else
+    eval "$COMMAND" >/dev/null || true
+  fi
+
+  debug "Switching Git working directory to target."
+  # Pull the rug out from under Git - make it use the target directory.
+  export GIT_WORK_TREE="$target_directory"
+
+  # If the directory doesn't already exist, create it, and don't show the diff.
+  if [ ! -d "$target_directory" ]; then
+    info "Making new directory. No changes are being overwritten."
+    mkdir -p "$target_directory"
+  else
+    info "Existing directory found. Changes that will be overwritten:"
+    # Try to condense the summary because otherwise the full contents of new additions will be
+    # displayed. Right now, reverse the output, so it makes more sense.
+    #
+    # As of writing, the Oracle JDK 11 image is based off of Oracle Linux 7.9 [1], which ships [2]
+    # Git version 1.8.3.1, and only seems to be receiving security updates. The Git developers
+    # simply did not add "--compact-summary" to any release notes, but it seems [3] to have been
+    # added in version 2.17.0. As such, we need to be able to fell back if --compact-summary is not
+    # available.
+    #
+    # [1] 7.7 for the Oracle JDK 8 image.
+    # [2] https://yum.oracle.com/repo/OracleLinux/OL7/latest/x86_64/index.html
+    # [3] https://github.com/git/git/commit/ddf88fa6166473be15822739e0a12aad4edfbbc5
+    git diff --color -R --compact-summary 2>/dev/null || git diff --color -R --summary
+  fi
+
+  debug "Updating server directory."
+  # Update the directory with new changes. Procede if failed, because if no commit was made, then
+  # there won't be a valid master branch to use.
+  git checkout -q -f master || true
+}
+
+# Given two directories setup by import_directory(), compare them for changes.
+# Arguments:
+#   - Path to the source directory.
+#   - Path to the target directory.
+#   - Path to output the patch to.
+# Outputs:
+#   - Status messages.
+# Variables Exported:
+#   - GIT_DIR: Location of the Git directory.
+#   - GIT_WORK_TREE: Location of the Git work tree.
+get_directory_changes() {
+  source_directory=$1
+  target_directory=$2
+  patch_path=$3
+
+  GIT_DIR="$(make_user_path "$source_directory")/.git-yamdi"
+  export GIT_DIR
+  export GIT_WORK_TREE="$target_directory"
+  if [ ! -d "$GIT_DIR" ]; then
+    info "No Git repo found. No changes."
+  else
+    info "Git repo found. Outputting changes to \"$patch_path\"."
+    git diff >"$patch_path"
+  fi
+}
+
+# Given a minimum, maximum and "both" value, generate a JVM memory option string. If both the
+# min and max and set, they will be use respectively. If only one is set, it will be used for
+# both.
+# Arguments:
+#   - Number of minimum MB.
+#   - Number of maximum MB.
+#   - Number to be used for both minimum and maximum MB.
+# Outputs:
+#   - The generated JVM option string.
+generate_memory_opts() {
+  minimum="$1"
+  maximum="$2"
+  both="$3"
+
+  if [ -n "$minimum" ] && [ -z "$maximum" ]; then
+    output="-Xms${minimum} -Xmx${minimum}"
+  elif [ -z "$minimum" ] && [ -n "$maximum" ]; then
+    output="-Xms${maximum} -Xmx${maximum}"
+  elif [ -n "$both" ]; then
+    output="-Xms${both} -Xmx${both}"
+  else
+    output="-Xms1024M -Xmx1024M"
+  fi
+
+  # See the setting of most of these options, in the main script.
+  if [ ! "$YAMDI_USE_SUGGESTED_JVM_OPTS" = false ]; then
+    # shellcheck disable=2154
+    if [ "$jvm_impl" = "openj9" ]; then
+      if [ -n "$maximum" ]; then
+        upper_bound="$maximum"
+      elif [ -n "$both" ]; then
+        upper_bound="$both"
+      else
+        upper_bound="1024"
+      fi
+      # Strip out the letter indicating the storage unit.
+      upper_bound=$(echo $upper_bound | grep -oE '[0-9]+')
+      # Set the nursery minimum to 50% of the heap size from 25%, to allow more space for short
+      # lived objects.
+      output="$output -Xmns$(("$upper_bound" / 2))M"
+      # Set the nursery maximum to 80% of the heap size to allow the server to grow it.
+      output="$output -Xmnx$(("$upper_bound" * 4 / 5))M"
+    fi
+  fi
+
+  echo "$output"
+}
 
 # Exits YAMDI, saving the patch for any changes that have been made to the configuration files by
 # the server. If the Java process seems to have crashed, the patch will not be created.
@@ -65,6 +271,8 @@ stop() {
   fi
 }
 
+info "Starting Yet Another Minecraft Docker Image."
+
 # Handle the SIGINT and SIGTERM signals. SIGINT is what is normally sent to a program when Ctrl+C
 # is pressed. The server handles this by quitting, without saving. SIGTERM is what is sent to a
 # program when "docker stop" or "docker-compose" is used. SIGTERM is also used when an active
@@ -77,12 +285,19 @@ stop() {
 trap "stop SIGINT" INT
 trap "stop SIGTERM" TERM
 
-# shellcheck source=src/yamdi-utils
-. yamdi-utils
-
-info "Starting Yet Another Minecraft Docker Image."
-
 # Setup variables that are expected to be set.
+# Set the directory for YAMDI data to be kept.
+export YAMDI_DIRECTORY="/opt/yamdi"
+# Set the directory for the server host configuration to be kept.
+export SERVER_CONFIG_HOST_DIRECTORY="$YAMDI_DIRECTORY/server-config-host"
+# Set the directory for the server host plugins to be kept.
+export SERVER_PLUGINS_HOST_DIRECTORY="$YAMDI_DIRECTORY/server-plugins-host"
+# Set the directory for user data to be kept.
+export USER_DIRECTORY="$YAMDI_DIRECTORY/user"
+# Set the directory for the server installation to be kept.
+export SERVER_DIRECTORY="$USER_DIRECTORY/server"
+# Set the directory for the command named pipe to be.
+export COMMAND_INPUT_FILE="/tmp/server-commmand-input"
 
 # Print and capture the Java version.
 info "Java version:"
@@ -263,14 +478,14 @@ versions/$YAMDI_MINECRAFT_VERSION/builds/$YAMDI_PAPER_BUILD")
   readonly build_json
 
   handle_curl_errors
-  build_json_error=$(echo "$build_json" | jq .error)
+  build_json_error=$(printf %s "$build_json" | jq .error)
   readonly builds_json_error
   if [ ! "null" = "$build_json_error" ]; then
     error "Failed to fetch Paper build info. Curl error: \"$build_json_error\"."
     exit 2
   fi
 
-  paper_build_jar_name=$(echo "$build_json" | jq .downloads.application.name | sed s/\"//g)
+  paper_build_jar_name=$(printf %s "$build_json" | jq .downloads.application.name | sed s/\"//g)
   readonly paper_build_jar_name
 
   paper_revision_jar="$SERVER_DIRECTORY/\
@@ -386,7 +601,7 @@ export JAVA_PID=$!
   #
   # The reason why we care about killing the "tail" process is that, if we don't do so, then the
   # "wait" command will wait indefinitely.
-  killall tail
+  kill "$(pidof tail)"
 ) &
 info "Waiting for Java process (PID $JAVA_PID) to exit."
 # Allow wait to return an error without making the whole script exit.
